apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-java-deployment
  namespace: arc
spec:
  replicas: 2 
  template:
    spec:
      repository: CMelerom/spring-framework-petclinic
      labels:
        - helm-gh-runner